language: ruby
rvm:
  - 2.3.4
cache: bundler

script:
  - bundle exec haml-lint source/
  - bundle exec scss-lint source/

deploy:
  provider: script
  script:
    - bundle exec rake build
    - bundle exec rake deploy
  on:
    branch: master
